microservice-chart: &microservice-chart
  namespace: "fdr"
  image:
    repository: ghcr.io/pagopa/pagopa-fdr-xml-to-json
    tag: "1.0.1-19-PAGOPA-2470-fix"
    pullPolicy: Always
  livenessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  readinessProbe:
    handlerType: tcpSocket
    tcpSocket:
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 12345 #jmx-exporter
    - 8080
  service:
    type: ClusterIP
    ports:
      - 8080
      - 12345 #jmx-exporter
  ingress: &ingress
    create: true
    host: "weuuat.fdr.internal.uat.platform.pagopa.it"
    path: /pagopa-fdr-xml-to-json/(.*)
    servicePort: 8080
  serviceAccount:
    name: "fdr-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources: &resources
    requests:
      memory: "768Mi"
      cpu: "0.25"
    limits:
      memory: "1Gi"
      cpu: "0.40"
  autoscaling: &autoscaling
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig: &envConfig
    #    JAVA_OPTS: "-XX:MaxHeapSize=576m -XX:MinHeapSize=64m"
    WEBSITE_SITE_NAME: "pagopafdrxmltojson" # required to show cloud role name in application insights
    FUNCTIONS_WORKER_RUNTIME: "java"
    FDR1_FLOW_BLOB_CONTAINER_NAME: "fdr1-flows"
    ERROR_TABLE_NAME: "fdr1conversionerror"
    BLOB_TRIGGER_POISON_QUEUE: "webjobs-blobtrigger-poison"
    FDR_NEW_BASE_URL: "https://api.uat.platform.pagopa.it/fdr-internal/service/v1"
    ADD_PAYMENT_REQUEST_PARTITION_SIZE: "1000"
    MAX_RETRY_COUNT: "5"
    ASPNETCORE_URLS: "http://*:8080"
    FUNCTIONS_SECRETS_PATH: "/tmp/secrets"
    AzureFunctionsWebHost__hostid: "fdr-xml-to-json"
  envFieldRef:
    APP_NAME: "metadata.labels['app.kubernetes.io/instance']"
    APP_VERSION: "metadata.labels['app.kubernetes.io/version']"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: "ai-connection-string"
    FDR_NEW_API_KEY: "fdr-internal-product-subscription-key"
    STORAGE_ACCOUNT_CONN_STRING: "fdr-sa-connection-string"
    AzureWebJobsStorage: "fdr-sa-connection-string"
  keyvault:
    name: "pagopa-u-fdr-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations:
    - key: dedicated
      operator: Equal
      value: "nodo"
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodo
                operator: In
                values:
                  - "true"
  canaryDelivery:
    create: false
# BLOB TRIGGER FUNCTION
blobtrigger:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /pagopa-fdr-xml-to-json/blobtrigger-notuser/(.*)
  autoscaling:
    !!merge <<: *autoscaling
  envConfig:
    !!merge <<: *envConfig
    WEBSITE_SITE_NAME: "pagopafdrxmltojson-blobtrigger" # required to show cloud role name in application insights
    AzureFunctionsWebHost__hostid: "fdr-xml-to-json-blob-trigger"
    AzureFunctionsJobHost__functions__0: "BlobEventProcessor"
# QUEUE TRIGGER FUNCTION
queuetrigger:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
    path: /pagopa-fdr-xml-to-json/queuetrigger-notuser/(.*)
  autoscaling:
    !!merge <<: *autoscaling
  envConfig:
    !!merge <<: *envConfig
    WEBSITE_SITE_NAME: "pagopafdrxmltojson-queuetrigger" # required to show cloud role name in application insights
    AzureFunctionsWebHost__hostid: "fdr-xml-to-json-queue-trigger"
    AzureFunctionsJobHost__functions__0: "QueueEventProcessor"
# HTTP TRIGGER FUNCTION
httptrigger:
  !!merge <<: *microservice-chart
  ingress:
    !!merge <<: *ingress
  autoscaling:
    !!merge <<: *autoscaling
  resources:
    !!merge <<: *resources
    requests:
      memory: "100Mi"
      cpu: "0.1"
    limits:
      memory: "768Mi"
      cpu: "0.40"
  envConfig:
    !!merge <<: *envConfig
    WEBSITE_SITE_NAME: "pagopafdrxmltojson-httptrigger" # required to show cloud role name in application insights
    AzureFunctionsWebHost__hostid: "fdr-xml-to-json-http-trigger"
    AzureFunctionsJobHost__functions__0: "Info"
    AzureFunctionsJobHost__functions__1: "XmlErrorRetry"
